"""add vehicle owner

Revision ID: 60e117502858
Revises: 80268df04c6f
Create Date: 2026-08-11 01:58:40.934472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e117502858'
down_revision: Union[str, Sequence[str], None] = '80268df04c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_foreign_key(None, 'vehicles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_column('vehicles', 'user_id')
    # ### end Alembic commands ###
